version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 909350318202.dkr.ecr.ap-southeast-1.amazonaws.com)
  build:
    commands:
      - docker build -t ecstestapp:latest .
      - docker tag ecstestapp:latest 909350318202.dkr.ecr.ap-southeast-1.amazonaws.com/ecstestapp:latest
  post_build:
    commands:
      - docker push 909350318202.dkr.ecr.ap-southeast-1.amazonaws.com/ecstestapp:latest
      - printf '[{"name":ecstestapp,"imageUri":"%s"}]' 909350318202.dkr.ecr.ap-southeast-1.amazonaws.com/ecstestapp:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
